### ISSUE TITLE
Instance Died a lot

### ISSUE THREAD

**Issue by kingpinn77** [jlplenio/crude-twitch-viewer-bot#100]
So many died instance
On the log always said :
- WARNING;0_42;Thread-33;instance;spawn_page;Cookie consent banner not found/clicked.

**Comment by kingpinn77** [comment]
here another log :

Traceback (most recent call last):
  File "ctvbot\instance.py", line 105, in start
  File "ctvbot\instance.py", line 175, in spawn_page
  File "playwright\sync_api\_generated.py", line 8114, in goto
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_page.py", line 495, in goto
  File "playwright\_impl\_frame.py", line 146, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 396, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: net::ERR_TIMED_OUT at https://www.twitch.tv/login

**Comment by kingpinn77** [comment]
here some logs : 

Traceback (most recent call last):
  File "ctvbot\instance.py", line 105, in start
  File "ctvbot\instance.py", line 201, in spawn_page
  File "playwright\sync_api\_generated.py", line 8114, in goto
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_page.py", line 495, in goto
  File "playwright\_impl\_frame.py", line 146, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 396, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.TimeoutError: Timeout 60000ms exceeded.

**Comment by unhiro** [comment]
playwright is timing out after 1 minute of the page not loading.

Could be a few things like slow/unreliable proxies, your or your servers internet is maxing out, or you are maxing out your memory or cpu. It is very resource intensive if the stream your are trying to view doesn't have transcode options(meaning video quality selections).

**Comment by kingpinn77** [comment]
thank u for this, it turn out my ISP problem, after they fixed it, all back to normal.
Thx for awesome Software!!

**Comment by jlplenio** [comment]
Glad to hear it works! Thank you, @unhiro
