### ISSUE TITLE
I'm getting this error

### ISSUE THREAD

**Issue by zeus122** [jlplenio/crude-twitch-viewer-bot#11]
when I run the source code gui_main.py i get this:
Traceback (most recent call last):
  File "C:\Users\Zeus\Desktop\crude-twitch-viewer-bot-master\main_gui.py", line 1, in <module>
    from gui import GUI
  File "C:\Users\Zeus\Desktop\crude-twitch-viewer-bot-master\gui.py", line 10, in <module>
    from spawner import BrowserManager
  File "C:\Users\Zeus\Desktop\crude-twitch-viewer-bot-master\spawner.py", line 8, in <module>
    from playwright.sync_api import sync_playwright
  File "C:\Python310\lib\site-packages\playwright\sync_api\__init__.py", line 25, in <module>
    import playwright.sync_api._generated
  File "C:\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "C:\Python310\lib\site-packages\playwright\_impl\_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "C:\Python310\lib\site-packages\playwright\_impl\_connection.py", line 22, in <module>
    from pyee import AsyncIOEventEmitter, EventEmitter
  File "C:\Python310\lib\site-packages\pyee\__init__.py", line 71, in <module>
    from pyee._trio import TrioEventEmitter  # noqa
  File "C:\Python310\lib\site-packages\pyee\_trio.py", line 4, in <module>
    import trio
  File "C:\Python310\lib\site-packages\trio\__init__.py", line 18, in <module>
    from ._core import (
  File "C:\Python310\lib\site-packages\trio\_core\__init__.py", line 29, in <module>
    from ._run import (
  File "C:\Python310\lib\site-packages\trio\_core\_run.py", line 22, in <module>
    from outcome import Error, Outcome, Value, capture
  File "C:\Python310\lib\site-packages\outcome\__init__.py", line 3, in <module>
    from ._impl import Error, Outcome, Value, acapture, capture
  File "C:\Python310\lib\site-packages\outcome\_impl.py", line 39, in <module>
    class Outcome(abc.ABC):
  File "C:\Python310\lib\site-packages\outcome\_impl.py", line 54, in Outcome
    _unwrapped = attr.ib(default=False, eq=False, init=False)
TypeError: attrib() got an unexpected keyword argument 'eq'

Process finished with exit code 1

can u help please

**Comment by jlplenio** [comment]
I tried with Python 3.8 and 3.10, and was unable to reproduce your error. Ideas - from within your venv, did you:
1. Install the requirements+versions from the [requirements.txt](https://github.com/jlplenio/crude-twitch-viewer-bot/blob/master/requirements.txt) via `pip install -r requirements.txt`?
2. Install the chrome browser for playwright via `python -m playwright install chrome`?

**Comment by jlplenio** [comment]
Please reopen, if your problem persists.
