### ISSUE TITLE
ERR_TUNNEL_CONNECTION_FAILED instant shutdown

### ISSUE THREAD

**Issue by diegozalez** [jlplenio/crude-twitch-viewer-bot#115]
- CTVBot version: [e.g. 0.4.0]
 - Windows version: [e.g. 10]

**Describe the bug**
I have tried the tool and it worked nicely and suddenly instants just die, I bought the 25 proxies in webshare.io and it worked but a few hours later it doesn't work, I now lunch the program, and hit spawn and the instance lunches follow by closing telling me to read logs and all I see is "ERR_TUNNEL_CONNECTION_FAILED", I have checked the proxy IP port usr and psw.

Thanks for the amazing tool hope i can make it work.

**logs**
2023-04-08 19:08:24,732;INFO;69_63;MainThread;manager;__init__;Manager start
2023-04-08 19:08:27,895;INFO;20_63;Thread-2;manager;spawn_instance_thread;Ordered instance 1, Thread-2, proxy http://185.195.62.138:6226
2023-04-08 19:08:27,895;INFO;0_63;Thread-2;manager;instance_status_report_callback;STARTING instance 1
2023-04-08 19:08:27,896;INFO;0_63;Thread-2;service;start;Restarter enabled.
2023-04-08 19:08:29,708;ERROR;52_63;Thread-2;instance;start;net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
Traceback (most recent call last):
  File "ctvbot\instance.py", line 105, in start
  File "ctvbot\instance.py", line 175, in spawn_page
  File "playwright\sync_api\_generated.py", line 8114, in goto
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_page.py", line 495, in goto
  File "playwright\_impl\_frame.py", line 146, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 396, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================

**Comment by diegozalez** [comment]
I have also tried without the proxy and it works.

**Comment by diegozalez** [comment]
I don't have High Concurrency but im only using 15 max

**Comment by diegozalez** [comment]
Okay the problem is that I reach the bandwidth limit of 250GB, it might be a problem is that I only stream in 1080p so I think they consume a lot. Can I fix this somehow ?

**Comment by jlplenio** [comment]
Good job on finding the solution on your own. CTVBot takes the lowest quality option available. 
I think that Twitch offers lower than source quality options based on overall server workload and streamer seniority. 
So check what quality option are available to find time window to save proxy bandwidth.

**Comment by diegozalez** [comment]
in my stream i only get the 1080p 60fps option, i think i had 13 instances and in only one night it reach the limit no more than 6h or 8h. i think with a bit of math we could calculate the exact time it takes.

**Comment by jlplenio** [comment]
True. If we assume that you stream at 6 Mbps, which equals to ~2.7 GB per hour:
With 13 instances watching for 7 hours, you would reach 250 GB traffic almost perfectly.
So, either you have to upgrade your proxy traffic or check if at some time more quality options are available.

**Comment by diegozalez** [comment]
![image](https://user-images.githubusercontent.com/22241049/232131244-eb703c69-4c37-423a-9e8f-642a1d7020c9.png)
this is in more detail, I now have the lower quality options but this month I have unlimited so I don't care anymore :)  for this month. by the way awesome tool, it's working very well, great job.
