### ISSUE TITLE
Proxy List User/Pass

### ISSUE THREAD

**Issue by SamirNazim** [jlplenio/crude-twitch-viewer-bot#12]
Where did you get access to Twitch user/pass to fill the proxy list? Am I missing something here? The instances keep dying otherwise. And if Headless is False, it brings me to a login page.

**Comment by jlplenio** [comment]
These are two different things:
- proxies in the [proxy_list.txt](https://github.com/jlplenio/crude-twitch-viewer-bot/blob/f2a77ac130aab01b3d8c8e148021a8e9421b3aa7/proxy/proxy_list.txt) are needed, if you want viewers to count as different people.
- user/pass for twitch is not implemented and therefore not needed.

You should only see the login page briefly, because after that, it will redirect to the desired channel page.
If the instances are still dying, please post the logs from the ctvb.log, and I'll take a look.

**Comment by SamirNazim** [comment]
```
2022-05-16 12:42:13,847;INFO;MainThread;spawner;__init__; Manager start
2022-05-16 12:42:17,275;INFO;Thread-2 (spawn_instance_thread);spawner;spawn_instance_thread; <Thread(Thread-2 (spawn_instance_thread), started 32492)> starting instance no 1
2022-05-16 12:42:19,289;INFO;Thread-3 (spawn_instance_thread);spawner;spawn_instance_thread; <Thread(Thread-3 (spawn_instance_thread), started 16516)> starting instance no 2
2022-05-16 12:42:21,289;INFO;Thread-4 (spawn_instance_thread);spawner;spawn_instance_thread; <Thread(Thread-4 (spawn_instance_thread), started 34492)> starting instance no 3
2022-05-16 12:42:40,229;ERROR;Thread-4 (spawn_instance_thread);spawner;start; Timeout 15000ms exceeded.
=========================== logs ===========================
waiting for selector "button[data-a-target=consent-banner-accept]"
============================================================
Traceback (most recent call last):
  File "c:\Users\samir\Desktop\crude-twitch-viewer-bot-master\crude-twitch-viewer-bot-master\spawner.py", line 175, in start
    self.spawn_page()
  File "c:\Users\samir\Desktop\crude-twitch-viewer-bot-master\crude-twitch-viewer-bot-master\spawner.py", line 245, in spawn_page
    self.page.click("button[data-a-target=consent-banner-accept]", timeout=15000)
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 8106, in click
    self._sync(
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_page.py", line 669, in click
    return await self._main_frame.click(**locals_to_params(locals()))
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 460, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 15000ms exceeded.
=========================== logs ===========================
waiting for selector "button[data-a-target=consent-banner-accept]"
============================================================
2022-05-16 12:42:40,243;ERROR;Thread-2 (spawn_instance_thread);spawner;start; Timeout 15000ms exceeded.
=========================== logs ===========================
waiting for selector "button[data-a-target=consent-banner-accept]"
============================================================
Traceback (most recent call last):
  File "c:\Users\samir\Desktop\crude-twitch-viewer-bot-master\crude-twitch-viewer-bot-master\spawner.py", line 175, in start
    self.spawn_page()
  File "c:\Users\samir\Desktop\crude-twitch-viewer-bot-master\crude-twitch-viewer-bot-master\spawner.py", line 245, in spawn_page
    self.page.click("button[data-a-target=consent-banner-accept]", timeout=15000)
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 8106, in click
    self._sync(
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_page.py", line 669, in click
    return await self._main_frame.click(**locals_to_params(locals()))
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 460, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 15000ms exceeded.
=========================== logs ===========================
waiting for selector "button[data-a-target=consent-banner-accept]"
============================================================
2022-05-16 12:42:40,244;ERROR;Thread-3 (spawn_instance_thread);spawner;start; Timeout 15000ms exceeded.
=========================== logs ===========================
waiting for selector "button[data-a-target=consent-banner-accept]"
============================================================
Traceback (most recent call last):
  File "c:\Users\samir\Desktop\crude-twitch-viewer-bot-master\crude-twitch-viewer-bot-master\spawner.py", line 175, in start
    self.spawn_page()
  File "c:\Users\samir\Desktop\crude-twitch-viewer-bot-master\crude-twitch-viewer-bot-master\spawner.py", line 245, in spawn_page
    self.page.click("button[data-a-target=consent-banner-accept]", timeout=15000)
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 8106, in click
    self._sync(
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_page.py", line 669, in click
    return await self._main_frame.click(**locals_to_params(locals()))
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 460, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\samir\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 15000ms exceeded.
=========================== logs ===========================
waiting for selector "button[data-a-target=consent-banner-accept]"
============================================================
```

**Comment by jlplenio** [comment]
Thank you for your log.
The program looks for the cookie consent/acceptance banner, does not find it and crashes — bad design on my part.
As you reported, you reach the login page. But somehow on your end/connection, the cookie banner is not shown.
It should work without this check. You can try it yourself by commenting out this line:
https://github.com/jlplenio/crude-twitch-viewer-bot/blob/f2a77ac130aab01b3d8c8e148021a8e9421b3aa7/spawner.py#L245

I'll make a change in the next release so that it continues even without finding the banner, but logs a warning.

**Comment by hoverage** [comment]
> Great, so it is now running. The only issue is that the views do not increase. This could be a proxy issue? I've been trying numerous ones. Is there a way to check if the proxies are good?
> 
> I'm using https://hidemy.name/en/proxy-checker/ and only loading in working proxies but still it won't increase channel views.
> 
> Proxies still show 0 even when I load the list btw.

+1 Used any proxy
