### ISSUE TITLE
Instance connects but dies 

### ISSUE THREAD

**Issue by HrvckRacer29** [jlplenio/crude-twitch-viewer-bot#124]
navigating to "https://www.twitch.tv/login", waiting until "load"

also why even mention "unstable support for Kick" when it doesn't even work with Kick in the first place? The instances don't even connect when you try to use a kick link.

**Comment by jlplenio** [comment]
The bot works as advertised. Please run through the troubleshooting to offer productive feedback:
https://github.com/jlplenio/crude-twitch-viewer-bot/wiki/Troubleshooting

**Comment by HrvckRacer29** [comment]
Instantly dies when launching an instance. Below is the ctvbot log file. I had it working for twitch up until recently and now it doesn't work. I tried unchecking the headless optio and it just launches an incognito chrome window about:blank and then closes out. Same for Kick. Does the same on my VPS. Below is on my laptop.


2023-05-05 17:10:59,007;INFO;57_44;MainThread;manager;__init__;Manager start
2023-05-05 17:11:06,401;INFO;4_43;Thread-2;manager;spawn_instance_thread;Ordered TWITCH instance 1, Thread-2, proxy (PROXYADDRESSWENTHERE)
2023-05-05 17:11:06,401;INFO;0_43;Thread-2;manager;instance_status_report_callback;STARTING instance 1
2023-05-05 17:11:06,401;INFO;0_43;Thread-2;service;start;Restarter enabled.
2023-05-05 17:11:08,599;ERROR;16_44;Thread-2;instance;start;net::ERR_HTTP_RESPONSE_CODE_FAILURE at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================ died at page about:blank
Traceback (most recent call last):
  File "ctvbot\instance.py", line 83, in start
  File "ctvbot\sites.py", line 103, in todo_after_spawn
  File "playwright\sync_api\_generated.py", line 8114, in goto
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_page.py", line 495, in goto
  File "playwright\_impl\_frame.py", line 146, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 396, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
2023-05-05 17:11:08,606;INFO;0_44;Thread-2;manager;instance_status_report_callback;SHUTDOWN instance 1
2023-05-05 17:11:08,606;INFO;0_44;Thread-2;service;stop;Restarter disabled.

**Comment by jlplenio** [comment]
Never saw this error. Does it work without proxy?

**Comment by HrvckRacer29** [comment]
It launched twitch.tv/login and then went to the specified stream without a proxy, i refreshed my proxy list and tried it again and it worked so something was blocking it?
Also possible in a future update to auto click for an over 18 banner for the program to start watching, i watched an instance on kick and i believe that is why it isnt turning green as you have to click the banner/accept to start watching. I dunno about the twitch side and over 18 banner.

**Comment by jlplenio** [comment]
Glad to hear it works for you! In the future we can edit the sites.py to add behavior specific to each site.
For example add the mature button click for kick or prepopulate the cookies to pre-accept the mature banner:
https://github.com/jlplenio/crude-twitch-viewer-bot/blob/45c0de9650855f66ed5e623b3b918ca8a360c5fa/ctvbot/sites.py#L59
