### ISSUE TITLE
The problem seems to have occurred since version 0.5.3 (including 0.5.5 as well

### ISSUE THREAD

**Issue by MRSSSMR** [jlplenio/crude-twitch-viewer-bot#156]
- CTVBot version?[0.5.5]
- OS with version? [Windows 10]
- Streaming platform? [twitch.tv]
- Proxies from webshare.io? [yes]
- 
Hello. I think there's a problem. I'm reporting
It was okay until 0.5.1 version

However, from version 0.5.3, when more than 100 people use bots, 
the above phrase started to appear
In the 0.5.1 version, 150 people could use it

May I know what the problem is?

![r1](https://github.com/jlplenio/crude-twitch-viewer-bot/assets/123009351/62df02c5-c1dd-4d8a-8b35-913cbe8d3805)

Traceback (most recent call last):
  File "ctvbot\instance.py", line 83, in start
  File "ctvbot\instance.py", line 102, in loop_and_check
  File "ctvbot\sites.py", line 94, in update_status
  File "playwright\sync_api\_generated.py", line 7611, in evaluate
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_page.py", line 411, in evaluate
  File "playwright\_impl\_frame.py", line 272, in evaluate
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 396, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: Target page, context or browser has been closed
2023-06-22 19:57:49,614;INFO;0_19;Thread-145;manager;instance_status_report_callback;SHUTDOWN instance 108

-------------------------------------------------------

**Comment by MRSSSMR** [comment]
When you add the sites.py file in 0.5.1 version, which is in 0.5.5 version
I think we can solve the problems that arise from some of the recent categories

If you know how to make an exe file
I'd appreciate it if you could share your tips

**Comment by MRSSSMR** [comment]
=========================== logs ===========================
navigating to "https://www.twitch.tv/Xxx", waiting until "load"
============================================================
2023-06-24 11:34:59,968;WARNING;100_77;Thread-254;instance;goto_with_retry;Instance 171 failed connection attempt #2.
2023-06-24 11:34:59,998;INFO;0_77;Thread-265;manager;instance_status_report_callback;SHUTDOWN instance 182
2023-06-24 11:34:59,998;INFO;0_77;Thread-264;manager;instance_status_report_callback;SHUTDOWN instance 181
2023-06-24 11:35:15,934;WARNING;13_72;Thread-261;sites;todo_after_spawn;banner 18+ not found/clicked.
2023-06-24 11:35:15,934;INFO;0_72;Thread-261;manager;instance_status_report_callback;INITIALIZED instance 178
2023-06-24 11:35:19,982;WARNING;44_72;Thread-254;instance;goto_with_retry;Instance 171 failed connection attempt #3.
2023-06-24 11:35:19,982;ERROR;0_72;Thread-254;instance;start;Timeout 20000ms exceeded.
=========================== logs ===========================
navigating to "https://www.twitch.tv/Xxx", waiting until "load"
============================================================ died at page https://www.twitch.tv/XQC
Traceback (most recent call last):
  File "ctvbot\instance.py", line 82, in start
  File "ctvbot\sites.py", line 146, in todo_after_spawn
  File "ctvbot\instance.py", line 156, in goto_with_retry
  File "playwright\sync_api\_generated.py", line 8114, in goto
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_page.py", line 495, in goto
  File "playwright\_impl\_frame.py", line 146, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 396, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.TimeoutError: Timeout 20000ms exceeded.
=========================== logs ===========================
navigating to "https://www.twitch.tv/Xxx", waiting until "load"
============================================================
2023-06-24 11:35:20,002;INFO;100_72;Thread-254;manager;instance_status_report_callback;SHUTDOWN instance 171
2023-06-24 11:35:20,945;INFO;36_71;Thread-261;manager;instance_status_report_callback;WATCHING instance 178

I think it's because it takes longer to turn on multiple websites

It's just a guess, but as you pointed out
I think it's because of 20,000ms

For example
Before, if I wanted to turn on 80 at once, 60 would have survived
Currently, about 20 out of 80 survive

**Comment by MRSSSMR** [comment]
![save](https://github.com/jlplenio/crude-twitch-viewer-bot/assets/123009351/5681d816-f782-4f70-8703-95bcc168ebc1)

Personally, in 0.5.1 version, only the screen comes out
In the 0.6.0 version, the chatroom came out
I think we need a lot of resources

So...
I think the bot is dying because of time limits and heavy programs
What do you think?

**Comment by huyhuyvu01** [comment]
I got the same problem yesterday at version 0.6, proxies from webshare.io also. 17/20 proxies got TimedOutError: Timeout 20000ms

Here is the log file if u are interested.
[ctvbot.log](https://github.com/jlplenio/crude-twitch-viewer-bot/files/11973970/ctvbot.log)

**Comment by ghostinos** [comment]
up

**Comment by ghostinos** [comment]
help me plz  :( 



2024-03-25 02:42:23,026;INFO;0_31;Thread-21 (spawn_instance_thread);manager;spawn_instance_thread;Ordered UNKNOWN instance 11, Thread-21 (spawn_instance_thread), proxy http://45.94.47.66:8110, user_agent Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
2024-03-25 02:42:23,030;INFO;0_31;Thread-21 (spawn_instance_thread);manager;instance_status_report_callback;STARTING instance 11
2024-03-25 02:42:28,175;WARNING;40_31;Thread-2 (spawn_instance_thread);instance;goto_with_retry;Instance 1 failed connection attempt #1.
2024-03-25 02:42:31,356;WARNING;23_31;Thread-20 (spawn_instance_thread);instance;goto_with_retry;Instance 10 failed connection attempt #1.
2024-03-25 02:42:31,608;WARNING;25_31;Thread-16 (spawn_instance_thread);instance;goto_with_retry;Instance 8 failed connection attempt #1.
2024-03-25 02:42:31,620;WARNING;16_31;Thread-20 (spawn_instance_thread);instance;goto_with_retry;Instance 10 failed connection attempt #2.
2024-03-25 02:42:39,845;WARNING;16_30;Thread-20 (spawn_instance_thread);instance;goto_with_retry;Instance 10 failed connection attempt #3.
2024-03-25 02:42:39,857;ERROR;100_30;Thread-20 (spawn_instance_thread);instance;start;net::ERR_TIMED_OUT at https://twitch.com/^^ died at page about:blank
Traceback (most recent call last):
  File "ctvbot\instance.py", line 95, in start
  File "ctvbot\sites.py", line 30, in todo_after_spawn
  File "ctvbot\instance.py", line 177, in goto_with_retry
  File "playwright\sync_api\_generated.py", line 9327, in goto
  File "playwright\_impl\_sync_base.py", line 115, in _sync
  File "playwright\_impl\_page.py", line 484, in goto
  File "playwright\_impl\_frame.py", line 149, in goto
  File "playwright\_impl\_connection.py", line 63, in send
