### ISSUE TITLE
Got blocked by CloufFlare on Kik

### ISSUE THREAD

**Issue by UNTAMEDHero** [jlplenio/crude-twitch-viewer-bot#160]
**Please answer the following questions:**
- CTVBot version? 0.6.0
- OS with version? Windows 10
- Streaming platform? kick.com
- Proxies from webshare.io? yes

**Describe the bug**  
Few days ago i could easly use your app, i tried new version now & firstly it says that my browser it's outdated, i took agent-list from previous version and it works but get kicked by cloudflare :(

**Logs**  
`-24 08:58:24,197;INFO;13_24;MainThread;manager;__init__;Manager start on Windows-10-10.0.19045-SP0
2023-06-24 08:58:32,535;INFO;6_24;Thread-2;manager;spawn_instance_thread;Ordered KICK instance 1, Thread-2, proxy http://blablabla, user_agent Mozilla/5.0 (iPad; CPU OS 12_5_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Mobile/15E148 Safari/604.1
2023-06-24 08:58:32,539;INFO;0_24;Thread-2;manager;instance_status_report_callback;STARTING instance 1
2023-06-24 08:58:32,542;INFO;0_24;Thread-2;service;start;Restarter enabled.
2023-06-24 08:58:44,147;ERROR;11_24;Thread-2;instance;start;Blocked by Cloudflare. died at page https://www.kick.com/blablabla
Traceback (most recent call last):
  File "ctvbot\instance.py", line 82, in start
  File "ctvbot\sites.py", line 138, in todo_after_spawn
ctvbot.utils.CloudflareBlockException: Blocked by Cloudflare.
2023-06-24 08:58:44,157;INFO;0_24;Thread-2;manager;instance_status_report_callback;SHUTDOWN instance 1
2023-06-24 08:58:44,161;INFO;4_24;Thread-2;service;stop;Restarter disabled.`

**Comment by l3franc3** [comment]
Seems to be related to injection of cookies in KICK class:
`for key, value in self.local_storage.items():
            tosend = """window.localStorage.setItem('{key}','{value}');""".format(key=key, value=value)
            self.page.evaluate(tosend)`

Try version 0.5.1 which should not be flagged by Cloudfare

**Comment by jlplenio** [comment]
Is that so @l3franc3? Thank you for that clue, I will look into it.

**Comment by jlplenio** [comment]
> Seems to be related to injection of cookies in KICK class: `for key, value in self.local_storage.items(): tosend = """window.localStorage.setItem('{key}','{value}');""".format(key=key, value=value) self.page.evaluate(tosend)`

I tested it and I don't see an impact of this statement. Cloudflare is tricky, and many things have to go right simultaneously.
For example, there is nothing the program, or you can do if your proxies are blacklisted by Cloudflare.

The best quick improvement I was able to find is to only use the following user-agent in the user-agent.txt:
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"

He seems to like it and 75% of my instances make it through.

**Comment by jlplenio** [comment]
Kick is very difficult, see my message above - there is only so much the tool can do. Did you try it with [webshare](https://www.webshare.io/?referral_code=w6nfvip4qp3g) proxies?

**Comment by jlplenio** [comment]
I made some progress regarding kick. Even in headless mode, 80% of my instances go through and are watching.

**Comment by jlplenio** [comment]
New Ko-fi version with kick support / cloudflare bypass here: https://github.com/jlplenio/crude-twitch-viewer-bot/discussions/256
