### ISSUE TITLE
Cloudflare fail kick.com

### ISSUE THREAD

**Issue by LOLToke** [jlplenio/crude-twitch-viewer-bot#162]
**Please answer the following questions:**
- CTVBot version? [e.g. 0.4.0]0.6.0
- OS with version? [e.g. Windows 10, Ubuntu 20.04] w10
- Streaming platform? [e.g. twitch.tv, kick.com, youtube.com] kick
- Proxies from webshare.io? Yes

**Describe the bug**  
2023-06-28 05:12:26,988;INFO;98_34;MainThread;manager;__init__;Manager start on Windows-10-10.0.19045-SP0
2023-06-28 05:12:43,231;INFO;68_34;Thread-2;manager;spawn_instance_thread;Ordered KICK instance 1, Thread-2, proxy no proxy, user_agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/537.86.5
2023-06-28 05:12:43,236;INFO;0_34;Thread-2;manager;instance_status_report_callback;STARTING instance 1
2023-06-28 05:12:43,239;INFO;50_34;Thread-2;service;start;Restarter enabled.
2023-06-28 05:12:57,806;ERROR;38_36;Thread-2;instance;start;Blocked by Cloudflare. died at page https://kick.com/*****
Traceback (most recent call last):
  File "ctvbot\instance.py", line 82, in start
  File "ctvbot\sites.py", line 138, in todo_after_spawn
ctvbot.utils.CloudflareBlockException: Blocked by Cloudflare.
2023-06-28 05:12:57,829;INFO;0_36;Thread-2;manager;instance_status_report_callback;SHUTDOWN instance 1
2023-06-28 05:12:57,834;INFO;0_36;Thread-2;service;stop;Restarter disabled.

**Comment by jlplenio** [comment]
Please seee #160
