### ISSUE TITLE
died at page https://www.twitch.tv/login

### ISSUE THREAD

**Issue by MissMaya23** [jlplenio/crude-twitch-viewer-bot#189]
- CTVBot version - 0.6.1 (current)
- OS with version - Windows 11
- Streaming platform - twitch.tv
- Proxies from webshare.io - yes

Program working as intended for almost 1 month with no issues, now receiving the following error.

**Logs**  
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
2023-09-10 08:22:14,859;INFO;18_36;Thread-4;manager;instance_status_report_callback;SHUTDOWN instance 2
2023-09-10 08:22:17,036;WARNING;2_36;Thread-5;instance;goto_with_retry;Instance 3 failed connection attempt #3.
2023-09-10 08:22:17,038;ERROR;0_36;Thread-5;instance;start;Timeout 20000ms exceeded.
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================ died at page https://www.twitch.tv/login
Traceback (most recent call last):
  File "ctvbot\instance.py", line 82, in start
  File "ctvbot\sites.py", line 202, in todo_after_spawn
  File "ctvbot\instance.py", line 156, in goto_with_retry
  File "playwright\sync_api\_generated.py", line 9293, in goto
  File "playwright\_impl\_sync_base.py", line 109, in _sync
  File "playwright\_impl\_page.py", line 479, in goto
  File "playwright\_impl\_frame.py", line 147, in goto
  File "playwright\_impl\_connection.py", line 61, in send
  File "playwright\_impl\_connection.py", line 482, in wrap_api_call
  File "playwright\_impl\_connection.py", line 97, in inner_send
playwright._impl._api_types.TimeoutError: Timeout 20000ms exceeded.
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
2023-09-10 08:22:17,046;INFO;9_36;Thread-5;manager;instance_status_report_callback;SHUTDOWN instance 3
2023-09-10 08:22:17,048;INFO;0_36;Thread-5;service;stop;Restarter disabled.

**Comment by jlplenio** [comment]
TimeoutError could indicate that either your system or traffic are at capacity.
On how many instances does this error occur, and what is your CPU/RAM at that time?
If the stream you are watching only allows for source quality, e.g., 1080p60, this also eats a lot of traffic.
This could max out your home internet bandwidth and or the bandwidth/concurrency from the proxy package.

**Comment by MissMaya23** [comment]
I am unable to spawn even a single instance. Previously I was doing up to
100. I have a top of the line system, 128gb ram, with an i9.

I have 20% of my proxy bandwidth still available (200gb)

A fresh log print in hopes it helps troubleshoot.

2023-09-11 06:27:56,935;INFO;57_8;MainThread;manager;__init__;Manager start
on Windows-10-10.0.19045-SP0
2023-09-11
06:28:32,448;INFO;3_8;Thread-2;manager;spawn_instance_thread;Ordered TWITCH
instance 1, Thread-2, proxy http://194.39.32.228:6525, user_agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/73.0.3683.103 Safari/537.36
2023-09-11
06:28:32,452;INFO;0_8;Thread-2;manager;instance_status_report_callback;STARTING
instance 1
2023-09-11 06:28:32,454;INFO;0_8;Thread-2;service;start;Restarter enabled.
2023-09-11
06:28:53,444;WARNING;4_8;Thread-2;instance;goto_with_retry;Instance 1
failed connection attempt #1.
2023-09-11
06:29:13,452;WARNING;4_8;Thread-2;instance;goto_with_retry;Instance 1
failed connection attempt #2.
2023-09-11
06:29:33,459;WARNING;4_8;Thread-2;instance;goto_with_retry;Instance 1
failed connection attempt #3.
2023-09-11 06:29:33,463;ERROR;0_8;Thread-2;instance;start;Timeout 20000ms
exceeded.
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================ died at page
https://www.twitch.tv/login
Traceback (most recent call last):
  File "ctvbot\instance.py", line 82, in start
  File "ctvbot\sites.py", line 202, in todo_after_spawn
  File "ctvbot\instance.py", line 156, in goto_with_retry
  File "playwright\sync_api\_generated.py", line 9293, in goto
  File "playwright\_impl\_sync_base.py", line 109, in _sync
  File "playwright\_impl\_page.py", line 479, in goto
  File "playwright\_impl\_frame.py", line 147, in goto
  File "playwright\_impl\_connection.py", line 61, in send
  File "playwright\_impl\_connection.py", line 482, in wrap_api_call
  File "playwright\_impl\_connection.py", line 97, in inner_send
playwright._impl._api_types.TimeoutError: Timeout 20000ms exceeded.
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
2023-09-11
06:29:33,470;INFO;0_8;Thread-2;manager;instance_status_report_callback;SHUTDOWN
instance 1
2023-09-11 06:29:33,473;INFO;5_8;Thread-2;service;stop;Restarter disabled.

Thank you for the quick response, if we are able to fix this you will have
earned yourself a lifetime supporter!

Cheers!

**Comment by MissMaya23** [comment]
Ive confirmed the stream remains viewable in 160p , my webshare proxies have also reset without any help. I believe the issue is that it is navigating to a login page instead of the desired stream.

**Comment by MissMaya23** [comment]
O M E G A O O F 

I needed to update my proxy list manually as they reset on the webshare side of things.

**Comment by jlplenio** [comment]
Hey @MissMaya23, great that you fixed the error on your own. So the information and credentials of your webshare proxies were not up-to-date anymore?

**Comment by RetakerMZ** [comment]
> O M E G A O O F
> 
> I needed to update my proxy list manually as they reset on the webshare side of things.

how do you update the proxy list ?

**Comment by jlplenio** [comment]
For [webshare.io](https://www.webshare.io/?referral_code=w6nfvip4qp3g), I assume @MissMaya23 either 
a. redownloaded the proxy list, maybe some proxies credentials changed/were outdated.
b. used the replace-option in webshare, to get completely fresh proxies.
