### ISSUE TITLE
Youtube viewer not working

### ISSUE THREAD

**Issue by Etharito** [jlplenio/crude-twitch-viewer-bot#213]
**Please answer the following questions:**
- CTVBot version? 0.6.1
- OS with version? Windows 10
- Streaming platform? Youtube
- Proxies from webshare.io? Yes

**Describe the bug**  
Well my instance dies and gives this error which i have pasted in the logs below. Its happening for Youtube live as well as youtube videos

**Logs**  
2023-10-11 13:06:56,892;ERROR;26_57;Thread-18;instance;start;Execution context was destroyed, most likely because of a navigation died at page https://www.youtube.com/watch?
Traceback (most recent call last):
  File "ctvbot\instance.py", line 83, in start
  File "ctvbot\instance.py", line 102, in loop_and_check
  File "ctvbot\sites.py", line 72, in update_status
  File "playwright\sync_api\_generated.py", line 8694, in evaluate
  File "playwright\_impl\_sync_base.py", line 109, in _sync
  File "playwright\_impl\_page.py", line 395, in evaluate
  File "playwright\_impl\_frame.py", line 277, in evaluate
  File "playwright\_impl\_connection.py", line 61, in send
  File "playwright\_impl\_connection.py", line 482, in wrap_api_call
  File "playwright\_impl\_connection.py", line 97, in inner_send
playwright._impl._api_types.Error: Execution context was destroyed, most likely because of a navigation

**Comment by jlplenio** [comment]
Thank you for your report. I will look into it.
