### ISSUE TITLE
ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by ayame1111** [jlplenio/crude-twitch-viewer-bot#217]
Im getting an error after trying to spawn an instance. Logs below.

```
2023-10-26 16:54:15,187;INFO;30_32;MainThread;manager;__init__;Manager start on Windows-10-10.0.22621-SP0
2023-10-26 16:54:23,249;INFO;4_32;Thread-2;manager;spawn_instance_thread;Ordered TWITCH instance 1, Thread-2, proxy http://154.194.10.217:6230, user_agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
2023-10-26 16:54:23,254;INFO;0_32;Thread-2;manager;instance_status_report_callback;STARTING instance 1
2023-10-26 16:54:23,259;INFO;0_32;Thread-2;service;start;Restarter enabled.
2023-10-26 16:54:24,142;WARNING;2_32;Thread-2;instance;goto_with_retry;Instance 1 failed connection attempt #1.
2023-10-26 16:54:24,156;WARNING;0_32;Thread-2;instance;goto_with_retry;Instance 1 failed connection attempt #2.
2023-10-26 16:54:24,171;WARNING;0_32;Thread-2;instance;goto_with_retry;Instance 1 failed connection attempt #3.
2023-10-26 16:54:24,180;ERROR;0_32;Thread-2;instance;start;net::ERR_EMPTY_RESPONSE at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================ died at page about:blank
Traceback (most recent call last):
  File "ctvbot\instance.py", line 82, in start
  File "ctvbot\sites.py", line 202, in todo_after_spawn
  File "ctvbot\instance.py", line 156, in goto_with_retry
  File "playwright\sync_api\_generated.py", line 9293, in goto
  File "playwright\_impl\_sync_base.py", line 109, in _sync
  File "playwright\_impl\_page.py", line 479, in goto
  File "playwright\_impl\_frame.py", line 147, in goto
  File "playwright\_impl\_connection.py", line 61, in send
  File "playwright\_impl\_connection.py", line 482, in wrap_api_call
  File "playwright\_impl\_connection.py", line 97, in inner_send
playwright._impl._api_types.Error: net::ERR_EMPTY_RESPONSE at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
2023-10-26 16:54:24,187;INFO;0_32;Thread-2;manager;instance_status_report_callback;SHUTDOWN instance 1
2023-10-26 16:54:24,192;INFO;0_32;Thread-2;service;stop;Restarter disabled.
2023-10-26 16:54:25,264;INFO;1_32;Thread-4;manager;spawn_instance_thread;Ordered TWITCH instance 1, Thread-4, proxy http://45.192.145.133:5475, user_agent Mozilla/5.0 (Windows NT 5.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
2023-10-26 16:54:25,269;INFO;0_32;Thread-4;manager;instance_status_report_callback;STARTING instance 1
2023-10-26 16:54:25,638;WARNING;2_32;Thread-4;instance;goto_with_retry;Instance 1 failed connection attempt #1.
2023-10-26 16:54:25,653;WARNING;13_32;Thread-4;instance;goto_with_retry;Instance 1 failed connection attempt #2.
2023-10-26 16:54:25,668;WARNING;4_32;Thread-4;instance;goto_with_retry;Instance 1 failed connection attempt #3.
2023-10-26 16:54:25,676;ERROR;0_32;Thread-4;instance;start;net::ERR_EMPTY_RESPONSE at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================ died at page about:blank
Traceback (most recent call last):
  File "ctvbot\instance.py", line 82, in start
  File "ctvbot\sites.py", line 202, in todo_after_spawn
  File "ctvbot\instance.py", line 156, in goto_with_retry
  File "playwright\sync_api\_generated.py", line 9293, in goto
  File "playwright\_impl\_sync_base.py", line 109, in _sync
  File "playwright\_impl\_page.py", line 479, in goto
  File "playwright\_impl\_frame.py", line 147, in goto
  File "playwright\_impl\_connection.py", line 61, in send
  File "playwright\_impl\_connection.py", line 482, in wrap_api_call
  File "playwright\_impl\_connection.py", line 97, in inner_send
playwright._impl._api_types.Error: net::ERR_EMPTY_RESPONSE at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
2023-10-26 16:54:25,683;INFO;0_32;Thread-4;manager;instance_status_report_callback;SHUTDOWN instance 1
2023-10-26 16:54:25,686;INFO;0_32;Thread-4;service;stop;Restarter disabled.
2023-10-26 16:54:27,270;INFO;1_32;Thread-5;manager;spawn_instance_thread;Ordered TWITCH instance 1, Thread-5, proxy http://154.194.10.159:6172, user_agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
2023-10-26 16:54:27,275;INFO;0_32;Thread-5;manager;instance_status_report_callback;STARTING instance 1
2023-10-26 16:54:27,652;WARNING;3_32;Thread-5;instance;goto_with_retry;Instance 1 failed connection attempt #1.
2023-10-26 16:54:27,670;WARNING;0_32;Thread-5;instance;goto_with_retry;Instance 1 failed connection attempt #2.
2023-10-26 16:54:27,685;WARNING;10_32;Thread-5;instance;goto_with_retry;Instance 1 failed connection attempt #3.
2023-10-26 16:54:27,694;ERROR;0_32;Thread-5;instance;start;net::ERR_EMPTY_RESPONSE at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================ died at page about:blank
Traceback (most recent call last):
  File "ctvbot\instance.py", line 82, in start
  File "ctvbot\sites.py", line 202, in todo_after_spawn
  File "ctvbot\instance.py", line 156, in goto_with_retry
  File "playwright\sync_api\_generated.py", line 9293, in goto
  File "playwright\_impl\_sync_base.py", line 109, in _sync
  File "playwright\_impl\_page.py", line 479, in goto
  File "playwright\_impl\_frame.py", line 147, in goto
  File "playwright\_impl\_connection.py", line 61, in send
  File "playwright\_impl\_connection.py", line 482, in wrap_api_call
  File "playwright\_impl\_connection.py", line 97, in inner_send
playwright._impl._api_types.Error: net::ERR_EMPTY_RESPONSE at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
2023-10-26 16:54:27,702;INFO;0_32;Thread-5;manager;instance_status_report_callback;SHUTDOWN instance 1
2023-10-26 16:54:27,708;INFO;0_32;Thread-5;service;stop;Restarter disabled.
```

**Comment by ayame1111** [comment]
forgot to mention version - CTVBot_KOFI_v4_CHAT_PAIRS_0.7.1_20231004_Windows
bought 100 proxies from referall link.

**Comment by STCMFILMZ** [comment]
is there a fix for this? ive been having the same problem........

**Comment by jlplenio** [comment]
It looks like the proxy connection was established, but the website could not be reached. The error is sadly quite generic. 
Can you please test the tool with an empty proxy_list.txt, i.e. no proxies - does it work?

**Comment by ayame1111** [comment]
no errors without proxies

```
2023-10-26 22:18:17,413;INFO;36_36;MainThread;manager;__init__;Manager start on Windows-10-10.0.22621-SP0
2023-10-26 22:18:17,421;INFO;44_36;MainThread;resource;build_token_list;Tokens loaded: 0
2023-10-26 22:18:17,428;INFO;25_36;MainThread;resource;build_pairs;Built twitch pair list and length of 0, from 0 tokens and 0 proxies.
2023-10-26 22:18:22,629;INFO;4_36;Thread-2;manager;spawn_instance_thread;Ordered TWITCH instance 1, Thread-2, proxy no proxy, user_agent Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
2023-10-26 22:18:22,635;INFO;0_36;Thread-2;manager;instance_status_report_callback;STARTING instance 1
2023-10-26 22:18:22,644;INFO;8_36;Thread-2;service;start;Restarter enabled.
```

**Comment by jlplenio** [comment]
So it suggests that there is a problem with the proxies. Or your system or network has a problem routing the proxies.
Can you check, if you can refresh/replace the proxies over at webshare? Or create a new account and test it with the 10 free proxies?

**Comment by ayame1111** [comment]
exactly the same error with newly created account - when it comes to network, any ideas how could i check that ?

**Comment by ayame1111** [comment]
is there any difference in premium proxy server and residential or static residential? should i try one of those options, or that cannot be the case?

**Comment by jlplenio** [comment]
No. It should not matter. Free, premium and private - all should work. Maybe try from a different network or different PC to exclude either.

**Comment by ayame1111** [comment]
works on different pc and network, looks like its something on my side then, wondering what...

**Comment by ayame1111** [comment]
did setup a VM and it works there, so it must be something with win 11, or NordVPN

**Comment by jlplenio** [comment]
Why NordVPN. Please disable that if you want to use the tool as this could cause routing problems.

**Comment by JustAMe56** [comment]
I understand why he uses an VPN, I do the same. If for whatever reason something goes wrong I don't want CTVB to use my own IP outside of the proxy list I give it. Since it would be a link between my stream and CTVB.

The VPN is the failsafe to prevent this.

**Comment by teletoobies** [comment]
I had same problem on Win 11, I changed to Win 10 - the problem gone. It doesn't seem to work well with Windows 11.
