### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by acok06** [jlplenio/crude-twitch-viewer-bot#223]
01:31:51,247;INFO;16_24;Thread-5;manager;spawn_instance_thread;Ordered TWITCH instance 1, Thread-5, proxy http://45.94.47.66:8110, user_agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7
2023-11-23 01:31:51,248;INFO;22_24;Thread-5;manager;instance_status_report_callback;STARTING instance 1
2023-11-23 01:31:52,534;WARNING;24_25;Thread-5;instance;goto_with_retry;Instance 1 failed connection attempt #1.
2023-11-23 01:31:52,693;WARNING;17_25;Thread-5;instance;goto_with_retry;Instance 1 failed connection attempt #2.
2023-11-23 01:31:52,850;WARNING;16_25;Thread-5;instance;goto_with_retry;Instance 1 failed connection attempt #3.
2023-11-23 01:31:52,852;ERROR;0_25;Thread-5;instance;start;net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================ died at page about:blank
Traceback (most recent call last):
  File "ctvbot\instance.py", line 82, in start
  File "ctvbot\sites.py", line 202, in todo_after_spawn
  File "ctvbot\instance.py", line 156, in goto_with_retry
  File "playwright\sync_api\_generated.py", line 9293, in goto
  File "playwright\_impl\_sync_base.py", line 109, in _sync
  File "playwright\_impl\_page.py", line 479, in goto
  File "playwright\_impl\_frame.py", line 147, in goto
  File "playwright\_impl\_connection.py", line 61, in send
  File "playwright\_impl\_connection.py", line 482, in wrap_api_call
  File "playwright\_impl\_connection.py", line 97, in inner_send
playwright._impl._api_types.Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"

**Comment by acok06** [comment]
its because of the proxies.
