### ISSUE TITLE
Private Pool Proxie

### ISSUE THREAD

**Issue by Bieuz** [jlplenio/crude-twitch-viewer-bot#23]
Hi jlpenio i use proxy like

**Comment by jlplenio** [comment]
Hey @Bieuz. I cannot test it, but it should work.
Just add your single rotating proxy to the [proxy_list.txt](https://github.com/jlplenio/crude-twitch-viewer-bot/blob/master/proxy/proxy_list.txt).
It will show only one available proxy, but it will be used over and over again.

**Comment by jlplenio** [comment]
I was able to try it on my end, and it worked with 

`beyondproxy.io:420:user:pass`

What does your ctvb.log say?

**Comment by Bieuz** [comment]
you can help me on discord?PLEASE i really want that... like 3 months working to search a good way to use proxies on programs bot

**Comment by Bieuz** [comment]
one of my paid proxie "work" but open twitch login screen don't go to the livescreen go to tab with login...

**Comment by Bieuz** [comment]
I don't get any errors it just doesn't work

**Comment by Bieuz** [comment]
My discord are Bieu#0003 send me your name... if want sorry i really want solve this... i think i need see your screen to understand idk

**Comment by thehackedone** [comment]
I am having the same issue beyondproxy.io:420:user:pass does not work nothing seems to work...

**Comment by thehackedone** [comment]
2022-07-12 01:33:02,070;INFO;MainThread;spawner;__init__; Manager start
2022-07-12 01:33:07,784;INFO;Thread-2;spawner;spawn_instance_thread; <Thread(Thread-2, started 28936)> starting instance no 1
2022-07-12 01:33:09,793;INFO;Thread-3;spawner;spawn_instance_thread; <Thread(Thread-3, started 27028)> starting instance no 2
2022-07-12 01:33:11,309;ERROR;Thread-2;spawner;start; net::ERR_PROXY_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
Traceback (most recent call last):
  File "spawner.py", line 176, in start
  File "spawner.py", line 236, in spawn_page
  File "playwright\sync_api\_generated.py", line 7413, in goto
  File "playwright\_impl\_sync_base.py", line 88, in _sync
  File "playwright\_impl\_page.py", line 493, in goto
  File "playwright\_impl\_frame.py", line 122, in goto
  File "playwright\_impl\_connection.py", line 39, in send
  File "playwright\_impl\_connection.py", line 63, in inner_send
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
2022-07-12 01:33:11,794;INFO;Thread-4;spawner;spawn_instance_thread; <Thread(Thread-4, started 2448)> starting instance no 3
2022-07-12 01:33:12,847;ERROR;Thread-3;spawner;start; net::ERR_PROXY_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================

**Comment by jlplenio** [comment]
Are your proxies HTTPS proxies by any chance?

https://github.com/jlplenio/crude-twitch-viewer-bot/blob/4fea1504e8e97b547ff64a232a184a3a00312695/proxy/proxy.py#L40

**Comment by Bieuz** [comment]
yes bro sorry for your waiting yes bro is http
