### ISSUE TITLE
macOS startup fails

### ISSUE THREAD

**Issue by jlplenio** [jlplenio/crude-twitch-viewer-bot#232]
### Discussed in https://github.com/jlplenio/crude-twitch-viewer-bot/discussions/230

<div type='discussions-op-text'>

<sup>Originally posted by **ivanwong12345** December 27, 2023</sup>
I was opening the .bin file by entering commands in terminal, and there are some errors:

Traceback (most recent call last):
  File "main_gui.py", line 24, in <module>
  File "ctvbot/gui.py", line 62, in __init__
  File "tkinter/__init__.py", line 2270, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
...
This probably means that Tcl wasn't installed properly.

[1978] Failed to execute script 'main_gui' due to unhandled exception!
Gui shutting down 2023-12-27

i tried the 0.6.0 same results</div>

**Comment by jlplenio** [comment]
I suspect this is internally related to #227 and is an error with pyinstaller packaging the executable incorrectly.
Can you tell me what CPU or Mac system you are using?
