### ISSUE TITLE
Error:net::ERR_TUNNEL_CONNECTION

### ISSUE THREAD

**Issue by empathist-dot** [jlplenio/crude-twitch-viewer-bot#249]
Reporting this issue because it didn't exist yesterday. Nothing changed on my machine.
I tried three different networks but the instance crashes immediately with the following error:

TWITCH Instance 1 died: Error:net::ERR_TUNNEL_CONNECTIO... Please see ctvbot.log.
TWITCH Instance 2 died: Error:net::ERR_TUNNEL_CONNECTIO... Please see ctvbot.log.
TWITCH Instance 1 died: Error:net::ERR_TUNNEL_CONNECTIO... Please see ctvbot.log.

**Please answer the following questions:**
- CTVBot version? [e.g. 0.4.0]   
0.6.1 
- OS with version? [e.g. Windows 10, Ubuntu 20.04]
Windows 10 and 11
- Streaming platform? [e.g. twitch.tv, kick.com, youtube.com]
Twitch.tv
- Proxies from webshare.io? [yes, no] 
Yes. The 10 free proxies.

**Logs**  
If applicable, post the part of the ctvbot.log, that refers to the problem.

```
2024-03-29 12:51:05,824;INFO;57_43;Thread-4;manager;spawn_instance_thread;Ordered TWITCH instance 2, Thread-4, proxy http://188.74.183.10:8279, user_agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
2024-03-29 12:51:05,834;INFO;42_43;Thread-4;manager;instance_status_report_callback;STARTING instance 2
2024-03-29 12:51:05,937;WARNING;60_43;Thread-2;instance;goto_with_retry;Instance 1 failed connection attempt #3.
2024-03-29 12:51:05,948;ERROR;0_43;Thread-2;instance;start;net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================ died at page chrome-error://chromewebdata/
Traceback (most recent call last):
  File "ctvbot\instance.py", line 82, in start
  File "ctvbot\sites.py", line 202, in todo_after_spawn
  File "ctvbot\instance.py", line 156, in goto_with_retry
  File "playwright\sync_api\_generated.py", line 9293, in goto
  File "playwright\_impl\_sync_base.py", line 109, in _sync
  File "playwright\_impl\_page.py", line 479, in goto
  File "playwright\_impl\_frame.py", line 147, in goto
  File "playwright\_impl\_connection.py", line 61, in send
  File "playwright\_impl\_connection.py", line 482, in wrap_api_call
  File "playwright\_impl\_connection.py", line 97, in inner_send
playwright._impl._api_types.Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
```

**Comment by empathist-dot** [comment]
Proxies expired. Didn't know the free webshare ones were this bad. Nevermind this issue.

**Comment by SzymenL0K0** [comment]
Have the same problem but my proxies are good and not expired

2024-04-09 22:29:27,781;INFO;8_49;MainThread;manager;__init__;Manager start on Windows-10-10.0.19045-SP0
2024-04-09 22:29:34,121;INFO;0_49;Thread-2 (spawn_instance_thread);manager;spawn_instance_thread;Ordered TWITCH instance 1, Thread-2 (spawn_instance_thread), proxy http://185.199.229.156:7492, user_agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36
2024-04-09 22:29:34,124;INFO;15_49;Thread-2 (spawn_instance_thread);manager;instance_status_report_callback;STARTING instance 1
2024-04-09 22:29:34,126;INFO;0_49;Thread-2 (spawn_instance_thread);service;start;Restarter enabled.
2024-04-09 22:29:35,314;WARNING;12_50;Thread-2 (spawn_instance_thread);instance;goto_with_retry;Instance 1 failed connection attempt #1.
2024-04-09 22:29:35,513;WARNING;3_50;Thread-2 (spawn_instance_thread);instance;goto_with_retry;Instance 1 failed connection attempt #2.
2024-04-09 22:29:35,700;WARNING;8_50;Thread-2 (spawn_instance_thread);instance;goto_with_retry;Instance 1 failed connection attempt #3.
2024-04-09 22:29:35,704;ERROR;0_50;Thread-2 (spawn_instance_thread);instance;start;net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login died at page chrome-error://chromewebdata/
Traceback (most recent call last):
  File "ctvbot\instance.py", line 88, in start
  File "ctvbot\sites.py", line 260, in todo_after_spawn
  File "ctvbot\instance.py", line 162, in goto_with_retry
  File "playwright\sync_api\_generated.py", line 9327, in goto
  File "playwright\_impl\_sync_base.py", line 115, in _sync
  File "playwright\_impl\_page.py", line 484, in goto
  File "playwright\_impl\_frame.py", line 149, in goto
  File "playwright\_impl\_connection.py", line 63, in send
  File "playwright\_impl\_connection.py", line 495, in wrap_api_call
  File "playwright\_impl\_connection.py", line 101, in inner_send
playwright._impl._errors.Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
2024-04-09 22:29:35,709;INFO;0_50;Thread-2 (spawn_instance_thread);manager;instance_status_report_callback;SHUTDOWN instance 1
2024-04-09 22:29:35,711;INFO;0_50;Thread-2 (spawn_instance_thread);service;stop;Restarter disabled.
