### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by LiamBMX** [jlplenio/crude-twitch-viewer-bot#252]
**Please answer the following questions:**
- CTVBot version? [e.g. 0.6.1]
- OS with version? [Windows 10,]
- Streaming platform? [twitch.tv]
- Proxies from webshare.io? [yes] 

**Describe the bug**  

(Page unreachable error when opening running)
**Screenshots**  
![image](https://github.com/jlplenio/crude-twitch-viewer-bot/assets/102465227/36401c86-76de-44bf-a27d-d0f4c5395e02)
**Logs**  
If applicable, post the part of the ctvbot.log, that refers to the problem.
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================ died at page chrome-error://chromewebdata/
Traceback (most recent call last):
  File "ctvbot\instance.py", line 82, in start
  File "ctvbot\sites.py", line 202, in todo_after_spawn
  File "ctvbot\instance.py", line 156, in goto_with_retry
  File "playwright\sync_api\_generated.py", line 9293, in goto
  File "playwright\_impl\_sync_base.py", line 109, in _sync
  File "playwright\_impl\_page.py", line 479, in goto
  File "playwright\_impl\_frame.py", line 147, in goto
  File "playwright\_impl\_connection.py", line 61, in send
  File "playwright\_impl\_connection.py", line 482, in wrap_api_call
  File "playwright\_impl\_connection.py", line 97, in inner_send
playwright._impl._api_types.Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
2024-03-30 00:32:41,095;INFO;100_50;Thread-2;manager;instance_status_report_callback;SHUTDOWN instance 1
2024-03-30 00:32:41,102;INFO;0_50;Thread-2;service;stop;Restarter disabled.

**Comment by 00escalona** [comment]
I´m having the same bug

**Comment by 00escalona** [comment]
Check the issue #249
