### ISSUE TITLE
Useragents Outdated

### ISSUE THREAD

**Issue by L30nard0100b** [jlplenio/crude-twitch-viewer-bot#286]
**Please answer the following questions:**
- CTVBot version? [e.g. 0.6.4]
- OS with version? [Windows 11]
- Streaming platform? [youtube.com]
- Proxies from webshare.io? [yes] 

**Describe the bug**  
Youtube doesn't support anymore some user agents with chrome 79 or below (this is what i noticed)

**Logs**  
2024-07-16 18:11:12,162;INFO;37_23;MainThread;manager;__init__;Manager start on Windows-10-10.0.22631-SP0
2024-07-16 18:11:22,557;INFO;0_22;Thread-2 (spawn_instance_thread);manager;spawn_instance_thread;Ordered YOUTUBE instance 1, Thread-2 (spawn_instance_thread), proxy http://207.244.217.165:6712, user_agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
2024-07-16 18:11:22,559;INFO;0_22;Thread-2 (spawn_instance_thread);manager;instance_status_report_callback;STARTING instance 1
2024-07-16 18:11:36,264;WARNING;1_23;Thread-2 (spawn_instance_thread);sites;todo_after_spawn;Cookie consent banner not found/clicked.
2024-07-16 18:11:36,399;INFO;0_23;Thread-4 (spawn_instance_thread);manager;spawn_instance_thread;Ordered YOUTUBE instance 2, Thread-4 (spawn_instance_thread), proxy http://64.64.118.149:6732, user_agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
2024-07-16 18:11:36,401;INFO;0_23;Thread-4 (spawn_instance_thread);manager;instance_status_report_callback;STARTING instance 2
2024-07-16 18:11:38,401;INFO;0_23;Thread-5 (spawn_instance_thread);manager;spawn_instance_thread;Ordered YOUTUBE instance 3, Thread-5 (spawn_instance_thread), proxy http://166.88.58.10:5735, user_agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4
2024-07-16 18:11:38,403;INFO;0_23;Thread-5 (spawn_instance_thread);manager;instance_status_report_callback;STARTING instance 3
2024-07-16 18:11:40,404;INFO;0_24;Thread-6 (spawn_instance_thread);manager;spawn_instance_thread;Ordered YOUTUBE instance 4, Thread-6 (spawn_instance_thread), proxy http://157.52.253.244:6204, user_agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
2024-07-16 18:11:40,406;INFO;0_24;Thread-6 (spawn_instance_thread);manager;instance_status_report_callback;STARTING instance 4
2024-07-16 18:11:52,035;WARNING;1_24;Thread-4 (spawn_instance_thread);sites;todo_after_spawn;Cookie consent banner not found/clicked.
2024-07-16 18:11:53,609;WARNING;1_24;Thread-5 (spawn_instance_thread);sites;todo_after_spawn;Cookie consent banner not found/clicked.
2024-07-16 18:11:55,939;WARNING;1_25;Thread-6 (spawn_instance_thread);sites;todo_after_spawn;Cookie consent banner not found/clicked.
2024-07-16 18:11:59,836;INFO;1_26;Thread-4 (spawn_instance_thread);manager;instance_status_report_callback;INITIALIZED instance 2
2024-07-16 18:12:03,544;INFO;1_26;Thread-6 (spawn_instance_thread);manager;instance_status_report_callback;INITIALIZED instance 4
2024-07-16 18:12:04,857;INFO;1_26;Thread-5 (spawn_instance_thread);manager;instance_status_report_callback;INITIALIZED instance 3
2024-07-16 18:12:06,674;ERROR;1_26;Thread-2 (spawn_instance_thread);instance;start;Timeout 30000ms exceeded. died at page https://www.youtube.com/supported_browsers?next_url=https%3A%2F%2F [youtube link that i dont want to show]
Traceback (most recent call last):
  File "ctvbot\instance.py", line 88, in start
  File "ctvbot\sites.py", line 163, in todo_after_spawn
  File "playwright\sync_api\_generated.py", line 8349, in wait_for_selector
  File "playwright\_impl\_sync_base.py", line 115, in _sync
  File "playwright\_impl\_page.py", line 357, in wait_for_selector
  File "playwright\_impl\_frame.py", line 327, in wait_for_selector
  File "playwright\_impl\_connection.py", line 63, in send
  File "playwright\_impl\_connection.py", line 495, in wrap_api_call
  File "playwright\_impl\_connection.py", line 101, in inner_send
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.
2024-07-16 18:12:06,680;INFO;0_26;Thread-2 (spawn_instance_thread);manager;instance_status_report_callback;SHUTDOWN instance 1
2024-07-16 18:12:09,961;INFO;1_26;Thread-4 (spawn_instance_thread);manager;instance_status_report_callback;WATCHING instance 2
2024-07-16 18:12:13,659;INFO;1_25;Thread-6 (spawn_instance_thread);manager;instance_status_report_callback;WATCHING instance 4
2024-07-16 18:12:14,972;INFO;1_25;Thread-5 (spawn_instance_thread);manager;instance_status_report_callback;WATCHING instance 3

**Comment by jlplenio** [comment]
Open this site with your standard Chrome browser and use the displayed user-agent as the only row in the useragent.txt file:
http://httpbin.org/user-agent
