### ISSUE TITLE
Instances always dieing

### ISSUE THREAD

**Issue by EchterDonut** [jlplenio/crude-twitch-viewer-bot#30]
I use the GUI Version of this programm. But they always die with the following error:
```
Traceback (most recent call last):
  File "spawner.py", line 66, in start
  File "spawner.py", line 130, in spawn_page
  File "playwright\sync_api\_generated.py", line 7285, in goto
  File "playwright\_impl\_sync_base.py", line 89, in _sync
  File "playwright\_impl\_page.py", line 496, in goto
  File "playwright\_impl\_frame.py", line 136, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 369, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
```

The proxies themself are working:
![image](https://user-images.githubusercontent.com/111557554/185552489-a4bc7828-289e-4007-ae6c-8834ce5b94cd.png)

Because they dont have auth I followed Issue this to add them: #27 

Hope you can help me.

**Comment by EchterDonut** [comment]
And btw before you ask: It doesnt even work with premium proxies from webshare

**Comment by jlplenio** [comment]
The proxies you showed in your screenshot look public, esp. because of the high latency. Public proxies won't work in general. 
As your proxies from webshare.io are not working either, it points to a problem with your system. Maybe firewall or network configuration. There is no way for me to diagnose this issue remotely.
You could send an email with one proxy from webshare.io, and I will verify that the issue is not with them.
