### ISSUE TITLE
Proxies not working. Todo improve logging.

### ISSUE THREAD

**Issue by YpvzuBohdygxn9257** [jlplenio/crude-twitch-viewer-bot#44]

**Comment by jlplenio** [comment]
Please inspect the ctvb.log in your root directory to assess why the instances are dying.

**Comment by YpvzuBohdygxn9257** [comment]
2022-09-21 12:19:40,302;INFO;MainThread;manager;__init__; Manager start
2022-09-21 12:19:48,942;INFO;Thread-2;manager;spawn_instance_thread; <Thread(Thread-2, started 23020)> starting instance no 1
2022-09-21 12:19:49,978;ERROR;Thread-2;spawner;start; net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
Traceback (most recent call last):
  File "spawner.py", line 66, in start
    self.spawn_page()
  File "spawner.py", line 130, in spawn_page
    self.page.goto("https://www.twitch.tv/login", timeout=100000)
  File "playwright\sync_api\_generated.py", line 7285, in goto
  File "playwright\_impl\_sync_base.py", line 89, in _sync
  File "playwright\_impl\_page.py", line 496, in goto
  File "playwright\_impl\_frame.py", line 136, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 369, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
2022-09-21 12:20:20,021;INFO;Thread-4;manager;spawn_instance_thread; <Thread(Thread-4, started 3116)> starting instance no 1
2022-09-21 12:20:20,921;ERROR;Thread-4;spawner;start; net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
Traceback (most recent call last):
  File "spawner.py", line 66, in start
    self.spawn_page()
  File "spawner.py", line 130, in spawn_page
    self.page.goto("https://www.twitch.tv/login", timeout=100000)
  File "playwright\sync_api\_generated.py", line 7285, in goto
  File "playwright\_impl\_sync_base.py", line 89, in _sync
  File "playwright\_impl\_page.py", line 496, in goto
  File "playwright\_impl\_frame.py", line 136, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 369, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
2022-09-21 12:20:22,036;INFO;Thread-5;manager;spawn_instance_thread; <Thread(Thread-5, started 16212)> starting instance no 1
2022-09-21 12:20:22,935;ERROR;Thread-5;spawner;start; net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
Traceback (most recent call last):
  File "spawner.py", line 66, in start
    self.spawn_page()
  File "spawner.py", line 130, in spawn_page
    self.page.goto("https://www.twitch.tv/login", timeout=100000)
  File "playwright\sync_api\_generated.py", line 7285, in goto
  File "playwright\_impl\_sync_base.py", line 89, in _sync
  File "playwright\_impl\_page.py", line 496, in goto
  File "playwright\_impl\_frame.py", line 136, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 369, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
2022-09-21 12:20:24,052;INFO;Thread-6;manager;spawn_instance_thread; <Thread(Thread-6, started 20468)> starting instance no 1
2022-09-21 12:20:24,956;ERROR;Thread-6;spawner;start; net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
Traceback (most recent call last):
  File "spawner.py", line 66, in start
    self.spawn_page()
  File "spawner.py", line 130, in spawn_page
    self.page.goto("https://www.twitch.tv/login", timeout=100000)
  File "playwright\sync_api\_generated.py", line 7285, in goto
  File "playwright\_impl\_sync_base.py", line 89, in _sync
  File "playwright\_impl\_page.py", line 496, in goto
  File "playwright\_impl\_frame.py", line 136, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 369, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================

**Comment by jlplenio** [comment]
The tool cannot reach twitch.tv through the proxies you provided. Please make sure to use working HTTP or SOCKS5 proxies.
An affordable source for working proxies can be found in the [Webshare Proxies Guide](https://github.com/jlplenio/crude-twitch-viewer-bot/wiki/Webshare.io-Proxies-Guide).

I will add improved logging to see which proxy failed, later. Move to beginning of method
https://github.com/jlplenio/crude-twitch-viewer-bot/blob/9bf4e1a60ba2bf7baebe5288cd6e99d5956f3d57/spawner.py#L159

**Comment by Lucifer192192** [comment]
I'm sure my agent can work,

But it doesn't work here

**Comment by jlplenio** [comment]
https://github.com/jlplenio/crude-twitch-viewer-bot/issues/44#issuecomment-1253639378 implemented in #57.
