### ISSUE TITLE
proxy is available but

### ISSUE THREAD

**Issue by Lucifer192192** [jlplenio/crude-twitch-viewer-bot#45]
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
Traceback (most recent call last):
  File "spawner.py", line 66, in start
  File "spawner.py", line 130, in spawn_page
  File "playwright\sync_api\_generated.py", line 7285, in goto
  File "playwright\_impl\_sync_base.py", line 89, in _sync
  File "playwright\_impl\_page.py", line 496, in goto
  File "playwright\_impl\_frame.py", line 136, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 369, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: net::ERR_CONNECTION_ABORTED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"

**Comment by Lucifer192192** [comment]
Code through self. Page. Goto (" https://www.twitch.tv/login ", the timeout = 100000)
die
