### ISSUE TITLE
Instance instant dead

### ISSUE THREAD

**Issue by maylis1510** [jlplenio/crude-twitch-viewer-bot#52]
Hello, I have just downloaded the software. I also installed proxies.
However when I launch an instance it dies directly.
I also have a problem that it does not open a chrome page for me like on the gif in the information.
I was wondering where this could be coming from, I think you can answer my question.
Here is a screen of the software to show you that I have the proxies that are detected etc.

![kjgvchgcjyc](https://user-images.githubusercontent.com/116885675/198574086-6043472b-ce1c-4cef-a5f9-69231f64351a.png)

**Comment by jlplenio** [comment]
Please check the ctvb.log file that is created in the same folder while the tool is running,

**Comment by maylis1510** [comment]
2022-10-28 14:30:14,432;INFO;MainThread;manager;__init__; Manager start
2022-10-28 14:30:18,631;INFO;Thread-2;manager;spawn_instance_thread; <Thread(Thread-2, started 46660)> starting instance no 1
2022-10-28 14:30:19,865;ERROR;Thread-2;spawner;start; Chromium distribution 'chrome' is not found at C:\Users\julie\AppData\Local\Google\Chrome\Application\chrome.exe
Run "playwright install chrome"
Traceback (most recent call last):
  File "spawner.py", line 66, in start
    if resume_time > self.last_active_resume_time:
  File "spawner.py", line 115, in spawn_page
    proxy_dict = self.proxy_dict
  File "playwright\sync_api\_generated.py", line 11458, in launch
  File "playwright\_impl\_sync_base.py", line 89, in _sync
  File "playwright\_impl\_browser_type.py", line 93, in launch
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 369, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: Chromium distribution 'chrome' is not found at C:\Users\julie\AppData\Local\Google\Chrome\Application\chrome.exe
Run "playwright install chrome"

From what I can understand it tells me that chrome is not installing.
I think you'll know better what it's all about with that.

**Comment by jlplenio** [comment]
Please install the Chrome browser and try again.

**Comment by maylis1510** [comment]
I reset my computer because there was a monstrous mess, everything works fine thank you, sorry for the inconvenience!
Best wishes

**Comment by jlplenio** [comment]
"Add a reason why an instance died in the log window of the user interface."
Added in #57.
