### ISSUE TITLE
Having this issue...

### ISSUE THREAD

**Issue by machoman555** [jlplenio/crude-twitch-viewer-bot#6]
Exception ignored in: <function BrowserSpawn.__del__ at 0x000001F77CEFA160>
Traceback (most recent call last):
Exception ignored in: <function BrowserSpawn.__del__ at 0x000001F77CEFA160>
Traceback (most recent call last):
Exception ignored in: <function BrowserSpawn.__del__ at 0x000001F77CEFA160>
  File "spawner.py", line 129, in __del__
Traceback (most recent call last):
  File "spawner.py", line 129, in __del__
AttributeError: 'BrowserSpawn' object has no attribute 'driver'
  File "spawner.py", line 129, in __del__
AttributeError: 'BrowserSpawn' object has no attribute 'driver'
AttributeError: 'BrowserSpawn' object has no attribute 'driver'

**Comment by jlplenio** [comment]
Hey, I can't derive the problem from the Traceback you posted. @machoman555 
Please try again, describe at which point the error occurs, and post the full Traceback.

**Comment by machoman555** [comment]
![Animation](https://user-images.githubusercontent.com/100002761/154825180-347bbfd7-f30c-437c-9bdf-9e719429df4f.gif)
@jlplenio 
I have 50 SOCKS5 great working proxies that I tested. So its definitely not proxies. 
I don't know what the problem is.

**Comment by jlplenio** [comment]
@machoman555 kudos for sending a gif in. I suspect the tool does not find your Chrome installation.
What Chrome version do you use?

**Comment by machoman555** [comment]
haha thanks! 

I am using Google Chrome Version 98.0.4758.102 (Official Build) (64-bit) 

What would you recommend??? 

@jlplenio

**Comment by jlplenio** [comment]
I can reproduce the error. I am guessing something changed with v98 of Chrome. I am on it.

**Comment by machoman555** [comment]
You the best! ill be waiting for the new version!

**Comment by machoman555** [comment]
will you also release new CTVBS version ?

**Comment by jlplenio** [comment]
Please try again with https://github.com/jlplenio/twitch-viewer-bot-selenium/releases/tag/v0.0.2

**Comment by rydelek11** [comment]
![obraz](https://user-images.githubusercontent.com/39122430/155433387-1abbea33-4b91-4dd6-b056-6cebf069bfec.png)

i get errors after new update

**Comment by rydelek11** [comment]
for me working on socks5

**Comment by jlplenio** [comment]
Working for you @machoman555, @rydelek11 or anyone?

**Comment by machoman555** [comment]
@jlplenio haven't tried it yet will let you know soon

**Comment by Loyspc** [comment]
boas amigo eu estou tendo o mesmo problema dou deixar uma imagem a dizer o erro
![image](https://user-images.githubusercontent.com/102766657/161166995-94e2fffc-b929-451e-8278-eb4b215ce197.png)

**Comment by Loyspc** [comment]
estou a usar a versao mais recente do chorome 99..........

**Comment by Loyspc** [comment]
good friend I'm having the same problem I leave a picture to say the error.
I'm using the latest version of chorome 99...........

**Comment by Loyspc** [comment]
![image](https://user-images.githubusercontent.com/102766657/161174979-546a53d9-c180-43f3-8511-3260c18c10e1.png)

**Comment by jlplenio** [comment]
@Loyspc I assume you updated the chromedriver to match the version for your installed chrome?
Judging from your latest screenshot, the bot should work. Is the viewer count not increasing?

**Comment by Loyspc** [comment]
I think it's counting but it only counts 1, wasn't it supposed to open windows? (I uninstalled python and re-installed it and now it's giving other errors)

**Comment by Loyspc** [comment]
![image](https://user-images.githubusercontent.com/102766657/161356859-c0b979e0-6cc7-4964-8e51-ddf25341da05.png)

**Comment by Loyspc** [comment]
do you have discord ?

**Comment by miguelcarneiro1989** [comment]
Available proxies 10
Available window locations 20

DevTools listening on ws://127.0.0.1:55487/devtools/browser/41c3b40f-931e-4537-b63e-b5d363acacdb
[0407/030041.647:INFO:CONSOLE(1)] "Download the Apollo DevTools for a better development experience: https://chrome.google.com/webstore/detail/apollo-client-developer-t/jdkknkkbebbapilgoeccciglkfbmbnfm", source: https://static.twitchcdn.net/assets/vendor-009f55f5c69fe30a940d.js (1)
[0407/030042.940:INFO:CONSOLE(1)] "Amazon IVS Player SDK 1.9.0-twitch.2-rc.2", source: https://static.twitchcdn.net/assets/amazon-ivs-wasmworker.min-ada4a3db5c759a83148a.js (1)
[0407/030042.942:INFO:CONSOLE(1)] "Amazon IVS Player SDK 1.9.0-twitch.2-rc.2", source: https://static.twitchcdn.net/assets/amazon-ivs-wasmworker.min-ada4a3db5c759a83148a.js (1)
[0407/030045.086:INFO:CONSOLE(1)] "Download the Apollo DevTools for a better development experience: https://chrome.google.com/webstore/detail/apollo-client-developer-t/jdkknkkbebbapilgoeccciglkfbmbnfm", source: https://static.twitchcdn.net/assets/vendor-009f55f5c69fe30a940d.js (1)
[0407/030045.858:INFO:CONSOLE(1)] "Amazon IVS Player SDK 1.9.0-twitch.2-rc.2", source: https://static.twitchcdn.net/assets/amazon-ivs-wasmworker.min-ada4a3db5c759a83148a.js (1)
[0407/030045.864:INFO:CONSOLE(1)] "Amazon IVS Player SDK 1.9.0-twitch.2-rc.2", source: https://static.twitchcdn.net/assets/amazon-ivs-wasmworker.min-ada4a3db5c759a83148a.js (1)
[0407/030046.675:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.", source:  (0)
[0407/030047.636:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.", source:  (0)


can u help with this error ?

**Comment by jlplenio** [comment]
New and more robust incl. logging version v010 released. Please test again.
