### ISSUE TITLE
Instance gets destroy after checking - Tried different Proxies, but seems to be having a problem loading twitch.tv

### ISSUE THREAD

**Issue by UnderNahc** [jlplenio/crude-twitch-viewer-bot#82]
2023-01-12 11:42:42,747;INFO;28_67;MainThread;manager;__init__;Manager start
2023-01-12 11:42:44,649;INFO;12_66;Thread-2;manager;spawn_instance_thread;Ordered instance 1, Thread-2, proxy http://atlanta.us.socks.nordhold.net:1080
2023-01-12 11:42:44,649;INFO;0_66;Thread-2;manager;instance_status_report_callback;STARTING instance 1
2023-01-12 11:42:44,649;INFO;0_66;Thread-2;service;start;Restarter enabled.
2023-01-12 11:42:46,916;ERROR;26_66;Thread-2;instance;start;net::ERR_EMPTY_RESPONSE at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
Traceback (most recent call last):
  File "ctvbot\instance.py", line 105, in start
  File "ctvbot\instance.py", line 175, in spawn_page
  File "playwright\sync_api\_generated.py", line 8114, in goto
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_page.py", line 495, in goto
  File "playwright\_impl\_frame.py", line 146, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 396, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: net::ERR_EMPTY_RESPONSE at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================

**Comment by UnderNahc** [comment]
i unselected headless, I see it open the google tab, but itll instantly close

**Comment by jlplenio** [comment]
Please try without proxies to see if it works generally.
It looks like you are using socks proxies, which are not supported.
Please try again with HTTP proxies.

**Comment by jlplenio** [comment]
:: is correct. So it still looks like a proxy problem. Public proxies won't work. Please make sure your proxies are working and are of high quality to support the concurrent connections and bandwidth.

**Comment by UnderNahc** [comment]
Yup that seemed to be the Problem!

Others with same problem: YOU CANNOT USE FREE SHIT COPYPASTA PROXIES THEY AINT GONNA WORK

Your gonna actually have to get some good ones.
