### ISSUE TITLE
Instances Kill Instantly

### ISSUE THREAD

**Issue by Buubulle** [jlplenio/crude-twitch-viewer-bot#85]
**Describe the bug**

Hello when I launch the spawn the instance kills instant even with the right proxy (Webshare)

**Screenshots**

![Capture](https://user-images.githubusercontent.com/82315546/212698059-90b57c30-1a82-40e4-aaf2-8d05f4e66ce9.PNG)

**logs**

2023-01-16 15:09:29,446;INFO;MainThread;manager;__init__; Manager start
2023-01-16 15:09:42,170;INFO;Thread-2;manager;spawn_instance_thread; <Thread(Thread-2, started 28608)> starting instance no 1
2023-01-16 15:09:42,170;INFO;Thread-2;instance;spawn_page; STARTING:<Thread(Thread-2, started 28608)> instance 1, proxy http://45.155.68.129:8133
2023-01-16 15:09:43,574;ERROR;Thread-2;instance;start; net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================
Traceback (most recent call last):
  File "instance.py", line 87, in start
  File "instance.py", line 161, in spawn_page
  File "playwright\sync_api\_generated.py", line 8114, in goto
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_page.py", line 495, in goto
  File "playwright\_impl\_frame.py", line 146, in goto
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 396, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.twitch.tv/login
=========================== logs ===========================
navigating to "https://www.twitch.tv/login", waiting until "load"
============================================================

**Comment by jlplenio** [comment]
Quite unusual to see problems with webshare. Please download the newest version and try without proxies first.

**Comment by Buubulle** [comment]
After research I found the problem it came from the proxy list thank you for your speed
