### ISSUE TITLE
Timeout 15000ms exceeded

### ISSUE THREAD

**Issue by luscalopez** [jlplenio/crude-twitch-viewer-bot#86]
I'm trying to use the script and the instances are just buffered, I'm using webshare proxies, but this log problem is occurring below. can you help me?
Traceback (most recent call last):
  File "ctvbot\instance.py", line 105, in start
  File "ctvbot\instance.py", line 203, in spawn_page
  File "playwright\sync_api\_generated.py", line 7265, in wait_for_selector
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_page.py", line 368, in wait_for_selector
  File "playwright\_impl\_frame.py", line 317, in wait_for_selector
  File "playwright\_impl\_connection.py", line 43, in send
  File "playwright\_impl\_connection.py", line 396, in wrap_api_call
  File "playwright\_impl\_connection.py", line 78, in inner_send
playwright._impl._api_types.TimeoutError: Timeout 15000ms exceeded.
=========================== logs ===========================
waiting for selector ".persistent-player" to be visible
============================================================
2023-01-17 22:45:54,766;ERROR;53_54;Thread-17;instance;start;Timeout 15000ms exceeded.
=========================== logs ===========================
waiting for selector ".persistent-player" to be visible
============================================================

**Comment by jlplenio** [comment]
Seems like CTVBot cannot find the video player on your twitch page.
Make sure you use the default twitch channel url, e.g.: https://www.twitch.tv/ninja
