### ISSUE TITLE
I can't make the bot work (Help)

### ISSUE THREAD

**Issue by Mccleinplay** [jlplenio/crude-twitch-viewer-bot#96]
.

**Desktop (please complete the following information):**
 - CTVBot version: [e.g. 0.4.0]
 - Windows version: [e.g. 10]

**Describe the bug**
I can't make the bot work, I already bought the 100 proxies according to the guide, I put them in the .txt, it recognizes the 100 proxies but it keeps giving the same error: Spawning one instance. Please wait for alive & watching instances increase.
Instance 1 died: FileNotFoundError. Please see ctvbot.log.

I attach text from the ctvbot.log

**Screenshots**

**logs**
If applicable, post the part of the ctvbot.log, that refers to the problem.

2023-02-06 21:31:26,239;INFO;27_35;MainThread;manager;__init__;Manager start
2023-02-06 21:32:34,170;INFO;10_40;Thread-2;manager;spawn_instance_thread;Ordered instance 1, Thread-2, proxy http://45.157.125.107:5734
2023-02-06 21:32:34,171;INFO;0_40;Thread-2;manager;instance_status_report_callback;STARTING instance 1
2023-02-06 21:32:34,171;INFO;0_40;Thread-2;service;start;Restarter enabled.
2023-02-06 21:32:34,174;ERROR;0_40;Thread-2;instance;start;[WinError 2] El sistema no puede encontrar el archivo especificado
Traceback (most recent call last):
  File "ctvbot\instance.py", line 105, in start
  File "ctvbot\instance.py", line 158, in spawn_page
  File "playwright\sync_api\_context_manager.py", line 94, in start
  File "playwright\sync_api\_context_manager.py", line 87, in __enter__
  File "playwright\sync_api\_context_manager.py", line 67, in greenlet_main
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "playwright\_impl\_connection.py", line 215, in run_as_sync
  File "playwright\_impl\_connection.py", line 224, in run
  File "playwright\_impl\_transport.py", line 133, in connect
  File "playwright\_impl\_transport.py", line 121, in connect
  File "asyncio\subprocess.py", line 236, in create_subprocess_exec
  File "asyncio\base_events.py", line 1676, in subprocess_exec
  File "asyncio\windows_events.py", line 394, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 890, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

**Comment by jlplenio** [comment]
Is Chome installed?

**Comment by Mccleinplay** [comment]
> Is Chome installed?

Yes

**Comment by jlplenio** [comment]
Could you reinstall it please, only possible culprit I see so far.

**Comment by Mccleinplay** [comment]
> Could you reinstall it please, only possible culprit I see so far.


I already reinstalled it and the error persists :'(

**Comment by arampe** [comment]
It works fine , did u install the folder in C: ? Also try running the file as Administrator, if that fails try running on different machine ..Sent from my iPhoneOn Feb 7, 2023, at 12:52 PM, Mccleinplay ***@***.***> wrote:﻿

Could you reinstall it please, only possible culprit I see so far.

I already reinstalled it and the error persists :'(

**Comment by Mccleinplay** [comment]
obviously it is installed in C: I would like to know why it doesn't recognize google chrome when starting, the bot works on another computer, but I don't know why it doesn't on this computer, I just have to reinstall windows from scratch. Thanks anyway. 

PS: I have opened an issue to find out if the bandwidth consumption in the program can be regulated, because the 1000gb would only last a few days, I have tested with 6 instances for approximately 15 minutes and it consumed 311 mb

**Comment by jlplenio** [comment]
Please reopen if the problem persists.
